version: '3'
services:
  geosphere-web:                        # 前端node容器(运行nginx中的Vue项目)
    restart: always                     # 重启策略: 容器退出时总是重启容器
    image: constq/page:v1
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9009:80"                      # 映射端口
    networks:
      - geosphere-network-web          # 设置网卡

networks:
  geosphere-network-web:
    driver: bridge
