version: '2'

services:
  node:                        # 前端node容器(运行nginx中的Vue项目)
    # container_name: webapp
    # restart: always                     # 重启策略: 容器退出时总是重启容器
    # build:
    #   context: ../
    #   dockerfile: ./docker/Dockerfile-dev
    # environment:
    #   TZ: Asia/Shanghai
    # ports:
    #   - "3001:3001"                      # 映射端口
    container_name: webapp
    restart: always                     # 重启策略: 容器退出时总是重启容器
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ../:/app
    environment:
      TZ: Asia/Shanghai
    ports:
      - "3001:3001"                      # 映射端口
    command:
      - sh
      - -c
      - |
          npm config set registry https://registry.npm.taobao.org
          yarn
          yarn dev
