# node镜像
FROM node:14-alpine
# 维护者信息
LABEL maintainer="z5021996@vip.qq.com"

# 拷贝前端项目 当前目录下的所有文件到app目录下(./指当前所有的代码路径 .指上一步cd到app的路径)
COPY ../ /app

# 指定接下来的工作路径为/app  - 类似于cd命令
WORKDIR /app

# 设置淘宝npm镜像
RUN npm config set registry https://registry.npm.taobao.org

# 打包 - 目的：丢到nginx下跑
RUN yarn
RUN yarn dev
