import qinglong from '@/assets/logo/docker/qinglong.png'
import iyuu from '@/assets/logo/docker/iyuu.png'
import jellyfin from '@/assets/logo/often/jellyfin.png'

const index = [{
  name: 'Jellyfin',
  url: 'https://router.qzran.cn:8001/web/index.html',
  img: jellyfin,
  desc: '一个自由软件媒体系统，控制媒体管理和流媒体'
}, {
  name: '自动签到',
  url: 'https://router.qzran.cn:8005/',
  alias: 'qiandao',
  desc: '自定义自动签到框架'
}, {
  name: 'MusicPlayer',
  url: 'https://router.qzran.cn:8009/',
  alias: 'music',
  desc: '音乐聚合平台'
}, {
  name: 'qBittorrent',
  url: 'https://router.qzran.cn:8002/',
  alias: 'qbittorrent',
  desc: '下载平台'
}, {
  name: 'tinyMediaManager',
  url: 'https://router.qzran.cn:8004/',
  alias: 'tinyMediaManager',
  desc: '刮削app'
}, {
  name: 'calibre',
  url: 'https://router.qzran.cn:8007/',
  alias: 'calibre',
  desc: '图书管理'
}, {
  name: 'iyuu',
  url: 'https://router.qzran.cn:8008/',
  alias: 'music',
  desc: '一键辅种',
  img: iyuu
}, {
  name: 'xteve',
  url: 'https://router.qzran.cn:8010/',
  alias: 'xteve',
  desc: '电视直播服务'
}, {
  name: 'Chevereto',
  url: 'https://router.qzran.cn:8011/',
  alias: 'chevereto',
  desc: '图床'
}, {
  name: 'gohttpserver',
  url: 'https://router.qzran.cn:8012/',
  alias: 'yunpan',
  desc: '简易云盘'
}, {
  name: 'chrome',
  url: 'https://router.qzran.cn:8013/vnc.html',
  alias: 'chrome',
  desc: 'chrome浏览器'
}, {
  name: 'homeassistant',
  url: 'https://router.qzran.cn:8018/',
  alias: 'homeassistant',
  desc: '智能家居中枢'
}, {
  name: '京东签到v3',
  url: 'https://router.qzran.cn:8021/',
  alias: 'jd',
  desc: '京东自动签到v3'
}, {
  name: 'navidrome',
  url: 'https://router.qzran.cn:8028/',
  alias: 'airsonic',
  desc: '音乐播放器'
}, {
  name: 'baidupcs',
  url: 'https://router.qzran.cn:8023/',
  alias: 'baiduyun',
  desc: '百度网盘下载器'
}, {
  name: 'cloudDrive',
  url: 'https://router.qzran.cn:8024/',
  alias: 'cloudDrive',
  desc: '云盘挂载器（115、阿里）'
}, {
  name: '青龙面板',
  url: 'https://router.qzran.cn:8025/',
  alias: 'music',
  desc: '各种脚本运行平台，包含京东签到',
  img: qinglong
}, {
  name: 'chesesubfinder',
  url: 'https://router.qzran.cn:8029/',
  alias: 'chesesubfinder',
  desc: '自动下载中文字幕'
}, {
  name: 'nas-tool',
  url: 'https://router.qzran.cn:8030/',
  alias: 'nas-tool',
  desc: 'nas影音一站式服务'
}, {
  name: 'jackett',
  url: 'https://router.qzran.cn:8031/',
  alias: 'jackett',
  desc: '种子索引服务'
}, {
  name: 'flaresolverr',
  url: 'https://router.qzran.cn:8032/',
  alias: 'flaresolverr',
  desc: '种子索引服务'
}, {
  name: 'hlink',
  url: 'https://router.qzran.cn:8033/',
  alias: 'hlink',
  desc: '硬链接服务'
}, {
  name: 'reader',
  url: 'https://router.qzran.cn:8035/',
  alias: 'reader',
  desc: '漫画阅读器'
}, {
  name: 'lanraragi',
  url: 'https://router.qzran.cn:8036/',
  alias: 'lanraragi',
  desc: '漫画阅读器'
}, {
  name: 'Tachidesk',
  url: 'https://router.qzran.cn:8037/',
  alias: 'Tachidesk',
  desc: '漫画聚合阅读器'
}, {
  name: 'ddns-go',
  url: 'https://router.qzran.cn:8038/',
  alias: 'ddns-go',
  desc: 'ddns服务'
}]

export default index
